# Generated by Django 5.1.7 on 2025-04-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabalheConosco', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='curriculo',
            field=models.FileField(upload_to=''),
        ),
    ]
