# Generated by Django 5.1.7 on 2025-04-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inscritos',
            fields=[
                ('id_inscrito', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.TextField(max_length=100)),
            ],
        ),
    ]
