# Generated by Django 5.1.7 on 2025-04-11 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscritos',
            old_name='email',
            new_name='emailsub',
        ),
    ]
